/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_thisfeng_ndkdemo2_JNI */

#ifndef _Included_com_thisfeng_ndkdemo2_JNI
#define _Included_com_thisfeng_ndkdemo2_JNI
#ifdef __cplusplus

/**
 *  此文件在\NDKDemo\app\src\main\java
执行命令：javah com.atguigu.ndkdemo.JNI
 （拷贝全类名，在文件中的 Class 名称右键 -> copy Reference 得到  com.thisfeng.ndkdemo2.JNI）
（生成的 .h头文件 会在当前 java 目录，将其拷贝进 jni 目录 或者 cpp 目录和 C文件统一存放）
（其实在 CMake 构建的话，可以不生成头文件，直接可以通过IDE 快速创建 C 对应的方法）

 */
extern "C" {
#endif
/*
 * Class:     com_thisfeng_ndkdemo2_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thisfeng_ndkdemo2_JNI_sayHello__
        (JNIEnv *, jobject);

/*
 * Class:     com_thisfeng_ndkdemo2_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_thisfeng_ndkdemo2_JNI_add
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_thisfeng_ndkdemo2_JNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thisfeng_ndkdemo2_JNI_sayHello__Ljava_lang_String_2
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thisfeng_ndkdemo2_JNI
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_thisfeng_ndkdemo2_JNI_increaseArrayEles
        (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_thisfeng_ndkdemo2_JNI
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_thisfeng_ndkdemo2_JNI_checkPwd
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
